# This is the config file. It's advisable to restart if any changes are made.

# The URL address to the AUTOMATIC1111 Web UI
url = "https://235c-35-240-161-86.eu.ngrok.io"

# Credentials when using --share and --gradio-auth
user = ""
pass = ""

# Credentials when using --api-auth
apiuser = ""
apipass = ""

# Whether or not to save outputs to disk ("True"/"False")
save_outputs = "True"

# The directory to save outputs (default = "outputs")
dir = "outputs"

# The limit of tasks a user can have waiting in queue (at least 1)
queue_limit = 1

# Whether or not buttons keep generating in batches ("True"/"False")
batch_buttons = "False"

# The maximum value allowed for width/height (keep as multiple of 64)
max_size = 1024

# The resize amount when using context menu Quick Upscale
quick_upscale_resize = 2.0

# AIYA won't generate if prompt has any words in the ban list
# Separate with commas; example, ["a", "b", "c"]
prompt_ban_list = []
# These words will be automatically removed from the prompt
prompt_ignore_list = []
# Choose whether or not ignored words are displayed to user
display_ignored_words = "False"
# These words will be added to the beginning of the negative prompt
negative_prompt_prefix = []


# the fallback channel defaults template for AIYA if nothing is set
negative_prompt = ""
data_model = ""
steps = 30
max_steps = 50
width = 512
height = 512
guidance_scale = "7.0"
sampler = "Euler a"
style = "None"
facefix = "None"
highres_fix = "Disabled"
clip_skip = 1
hypernet = "None"
hyper_multi = "0.85"
lora = "None"
lora_multi = "0.85"
strength = "0.75"
batch = "1,1"
max_batch = "1,1"
upscaler_1 = "ESRGAN_4x"
